In [1]:
#importing libraries
import numpy as np
import pandas as pd

In [2]:
#loading dataset
df = pd.read_csv('heart.csv')
df.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [3]:
#counting null
df.isna().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [4]:
#outlier by z-score

In [5]:
age = df['Age']
age_mean = np.mean(age)
age_std = np.std(age)
threshold = 3
outlier_age = []
for i in age:
    z = (i-age_mean)/age_std
    if z > threshold:
        outlier_age.append(i)
outlier_age

[]

In [6]:
restingBP = df['RestingBP']
restingBP_mean = np.mean(restingBP)
restingBP_std = np.std(restingBP)
threshold = 3
outlier_restingBP = []
for i in restingBP:
    z = (i-restingBP_mean)/restingBP_std
    if z > threshold:
        outlier_restingBP.append(i)
outlier_restingBP

[190, 200, 200, 200, 190, 200, 192]

In [7]:
cholesterol = df['Cholesterol']
cholesterol_mean = np.mean(cholesterol)
cholesterol_std = np.std(cholesterol)
threshold = 3
outlier_cholesterol = []
for i in cholesterol:
    z = (i-cholesterol_mean)/cholesterol_std
    if z > threshold:
        outlier_cholesterol.append(i)
outlier_cholesterol

[529, 603, 564]

In [8]:
fastingBS = df['FastingBS']
fastingBS_mean = np.mean(fastingBS)
fastingBS_std = np.std(fastingBS)
threshold = 3
outlier_fastingBS = []
for i in fastingBS:
    z = (i-fastingBS_mean)/fastingBS_std
    if z > threshold:
        outlier_fastingBS.append(i)
outlier_fastingBS

[]

In [9]:
maxHR = df['MaxHR']
maxHR_mean = np.mean(maxHR)
maxHR_std = np.std(maxHR)
threshold = 3
outlier_maxHR = []
for i in maxHR:
    z = (i-maxHR_mean)/maxHR_std
    if z > threshold:
        outlier_maxHR.append(i)
outlier_maxHR

[]

In [10]:
oldpeak = df['Oldpeak']
oldpeak_mean = np.mean(oldpeak)
oldpeak_std = np.std(oldpeak)
threshold = 3
outlier_oldpeak = []
for i in oldpeak:
    z = (i-oldpeak_mean)/oldpeak_std
    if z > threshold:
        outlier_oldpeak.append(i)
outlier_oldpeak

[5.0, 4.2, 5.6, 4.2, 6.2, 4.4]

In [11]:
heartDisease = df['HeartDisease']
heartDisease_mean = np.mean(heartDisease)
heartDisease_std = np.std(heartDisease)
threshold = 3
outlier_heartDisease = []
for i in heartDisease:
    z = (i-heartDisease_mean)/heartDisease_std
    if z > threshold:
        outlier_heartDisease.append(i)
outlier_heartDisease

[]

In [12]:
df.shape

(918, 12)

In [13]:
#removing outlier

In [14]:
i = df[df['RestingBP'].isin(outlier_restingBP)].index
df.drop(i, inplace=True)
df.shape

(911, 12)

In [15]:
i = df[df['Cholesterol'].isin(outlier_cholesterol)].index
df.drop(i, inplace=True)
df.shape

(908, 12)

In [16]:
i = df[df['Oldpeak'].isin(outlier_oldpeak)].index
df.drop(i, inplace=True)
df.shape

(902, 12)

In [17]:
df = pd.get_dummies(df, drop_first=True)
df.head()

Age  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak  HeartDisease  \
0   40        140          289          0    172      0.0             0   
1   49        160          180          0    156      1.0             1   
2   37        130          283          0     98      0.0             0   
3   48        138          214          0    108      1.5             1   
4   54        150          195          0    122      0.0             0   

   Sex_M  ChestPainType_ATA  ChestPainType_NAP  ChestPainType_TA  \
0   True               True              False             False   
1  False              False               True             False   
2   True               True              False             False   
3  False              False              False             False   
4   True              False               True             False   

   RestingECG_Normal  RestingECG_ST  ExerciseAngina_Y  ST_Slope_Flat  \
0               True          False             False          False   
1               True          False             False           True   
2              False           True             False          False   
3               True          False              True           True   
4               True          False             False          False   

   ST_Slope_Up  
0         True  
1        False  
2         True  
3        False  
4         True

In [18]:
df.describe()

Age   RestingBP  Cholesterol   FastingBS       MaxHR  \
count  902.000000  902.000000   902.000000  902.000000  902.000000   
mean    53.487805  131.854767   197.347007    0.232816  136.848115   
std      9.444115   17.682612   107.585613    0.422860   25.451226   
min     28.000000    0.000000     0.000000    0.000000   60.000000   
25%     47.000000  120.000000   173.000000    0.000000  120.000000   
50%     54.000000  130.000000   222.000000    0.000000  138.000000   
75%     60.000000  140.000000   266.000000    0.000000  156.000000   
max     77.000000  185.000000   518.000000    1.000000  202.000000   

          Oldpeak  HeartDisease  
count  902.000000    902.000000  
mean     0.857428      0.548780  
std      1.013157      0.497891  
min     -2.600000      0.000000  
25%      0.000000      0.000000  
50%      0.500000      1.000000  
75%      1.500000      1.000000  
max      4.000000      1.000000

In [19]:
x = df.drop('HeartDisease', axis=1)
x.head()

Age  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak  Sex_M  \
0   40        140          289          0    172      0.0   True   
1   49        160          180          0    156      1.0  False   
2   37        130          283          0     98      0.0   True   
3   48        138          214          0    108      1.5  False   
4   54        150          195          0    122      0.0   True   

   ChestPainType_ATA  ChestPainType_NAP  ChestPainType_TA  RestingECG_Normal  \
0               True              False             False               True   
1              False               True             False               True   
2               True              False             False              False   
3              False              False             False               True   
4              False               True             False               True   

   RestingECG_ST  ExerciseAngina_Y  ST_Slope_Flat  ST_Slope_Up  
0          False             False          False         True  
1          False             False           True        False  
2           True             False          False         True  
3          False              True           True        False  
4          False             False          False         True

In [20]:
y = df['HeartDisease']
y

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 902, dtype: int64

In [21]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_scale = scaler.fit_transform(x)
x_scale

array([[-1.42896269,  0.46089071,  0.85238015, ..., -0.82065181,
        -1.00221976,  1.13805334],
       [-0.47545956,  1.5925728 , -0.16132855, ..., -0.82065181,
         0.99778516, -0.87869344],
       [-1.74679706, -0.10495034,  0.79657967, ..., -0.82065181,
        -1.00221976,  1.13805334],
       ...,
       [ 0.37209878, -0.10495034, -0.61703246, ...,  1.21854359,
         0.99778516, -0.87869344],
       [ 0.37209878, -0.10495034,  0.35947592, ..., -0.82065181,
         0.99778516, -0.87869344],
       [-1.64085227,  0.3477225 , -0.20782894, ..., -0.82065181,
        -1.00221976,  1.13805334]])

In [22]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_scale, y, test_size=0.2, random_state=2)

In [23]:
x_train.shape

(721, 15)

In [24]:
y_test.shape

(181,)

In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
l_reg = LogisticRegression(C=0.5)
s_clf = SVC(C=0.5, kernel='rbf', gamma='auto')
r_clf = RandomForestClassifier(n_estimators=100, max_depth=10, max_samples=50, random_state=20)

In [26]:
l_reg.fit(x_train, y_train)
l_reg.score(x_test, y_test)

0.8674033149171271

In [27]:
s_clf.fit(x_train, y_train)
s_clf.score(x_test, y_test)

0.8784530386740331

In [28]:
r_clf.fit(x_train, y_train)
r_clf.score(x_test, y_test)

0.8729281767955801

In [29]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
pca.fit(x)
x_pca = pca.transform(x)
x_pca

array([[ 93.82516575, -29.40343477],
       [-15.58380044, -14.10534714],
       [ 83.29544144,  38.68553968],
       ...,
       [-67.57277874,  17.61565402],
       [ 40.70355216, -33.38308603],
       [-19.9132065 , -37.29321338]])

In [30]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_pca, y, test_size=0.2, random_state=2)

In [31]:
l_reg.fit(x_train, y_train)
l_reg.score(x_test, y_test)

0.7458563535911602

In [32]:
s_clf.fit(x_train, y_train)
s_clf.score(x_test, y_test)

0.6132596685082873

In [33]:
r_clf.fit(x_train, y_train)
r_clf.score(x_test, y_test)

0.7624309392265194

In [34]:
#PCA

In [35]:
from sklearn.decomposition import PCA
pca = PCA(0.98)
pca.fit(x)
x_pca1 = pca.transform(x)
x_pca1

array([[ 93.82516575, -29.40343477, -11.58755786],
       [-15.58380044, -14.10534714, -31.68225284],
       [ 83.29544144,  38.68553968,  15.39941453],
       ...,
       [-67.57277874,  17.61565402,   4.35145724],
       [ 40.70355216, -33.38308603,  -5.99050662],
       [-19.9132065 , -37.29321338, -13.31460928]])

In [36]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_pca1, y, test_size=0.2, random_state=2)

In [37]:
l_reg.fit(x_train, y_train)
l_reg.score(x_test, y_test)

0.7458563535911602

In [38]:
s_clf.fit(x_train, y_train)
s_clf.score(x_test, y_test)

0.5966850828729282

In [39]:
r_clf.fit(x_train, y_train)
r_clf.score(x_test, y_test)

0.7348066298342542

In [40]:
from sklearn.decomposition import PCA
pca = PCA(1)
pca.fit(x)
x_pca2 = pca.transform(x)
x_pca2

array([[ 9.38251657e+01],
       [-1.55838004e+01],
       [ 8.32954414e+01],
       [ 1.50868394e+01],
       [-2.86260856e+00],
       [ 1.43218762e+02],
       [ 4.15692163e+01],
       [ 1.04982358e+01],
       [ 9.53291102e+00],
       [ 8.53000657e+01],
       [ 1.40359562e+01],
       [-3.54714835e+01],
       [ 7.01085854e+00],
       [ 3.69664484e+01],
       [ 1.33995028e+01],
       [ 7.60409819e+01],
       [ 7.49315708e-02],
       [ 5.16386321e+00],
       [ 4.91642021e+01],
       [ 7.07976452e+01],
       [ 2.53646679e+01],
       [-1.31700603e+01],
       [ 5.13272151e+00],
       [ 9.16927836e+01],
       [ 1.77653222e+01],
       [ 1.41728919e+01],
       [ 6.09101911e+01],
       [ 8.51468216e+01],
       [ 2.69166907e+02],
       [-8.96127752e+00],
       [ 3.19878545e+02],
       [-3.16939499e+01],
       [ 2.55832171e+01],
       [-2.56307881e+01],
       [-9.85979653e+00],
       [ 5.76616834e+01],
       [ 1.05556721e+02],
       [ 5.25273011e+01],
       [-1.9

In [41]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_pca2, y, test_size=0.2, random_state=2)

In [42]:
l_reg.fit(x_train, y_train)
l_reg.score(x_test, y_test)

0.569060773480663

In [43]:
s_clf.fit(x_train, y_train)
s_clf.score(x_test, y_test)

0.6243093922651933

In [44]:
r_clf.fit(x_train, y_train)
r_clf.score(x_test, y_test)

0.585635359116022